### ISSUE TITLE
Checkbox save error

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#1148]
For large matrix fields, where pagination is required at `/task/fieldMatrix`, the "Save" function on one page clears the checkboxes for the other pages.

**Comment by WebDevJL** [comment]
Since I'm working on the field data, I came across this issue and I would share my opinion. We need to load all the data into the page and use jQuery to hide/show the pages. Then the checkboxes status is retained as long as the  user doesn't leave the page. Clicking save will save all the data.

**Comment by bsaiken** [comment]
See https://github.com/FWAJL/FieldWorkManager/issues/1207#issuecomment-134603652

**Comment by gsouvik** [comment]
@bsaiken 
I've changed the field data matrix UI structure as per your comment from #1207 . Please note I've done this only for the field data matrix section as I wanted you to review this and let me know if you really liked it. I had to completely change the HTML structure to fit it into our new requirement of scroll-able div with no pagination, so I just wanted to get it approved before touching the lab analyte matrix UI. 

All your CSS instructions are implemented as well.

I've also introduced the second line text for Analyte name. Please note the script at this point doesn't consider breaking the text on "white space" character, instead it just breaks the text after 15 characters, even if a word breaks into two and gets into the second line. Let me show you a screenshot:
![screen shot 2015-08-26 at 9 01 03 pm](https://cloud.githubusercontent.com/assets/2292482/9498092/b88305e2-4c35-11e5-83ff-d68da061a12c.png)

Notice how the word "Name" is broken into the second line. If you want the script to be more intelligent and break into second line on the space just before the word "Name", a bit of more programming would be required. I just wanted to show you visually and know your feedback before implementing it. 

Let me know your thoughts and I shall replicate this to the lab matrix screen as well. Code is pushed to feature_devsupport.

**Comment by bsaiken** [comment]
@gsouvik 
That is much better!
Let's fix the text as you describe so it does not break a word. 

Here is one other improvement.  Use two separate rows to make the header rows and put the units (always trailing text in parens) in the second row.  See the photo attached.  

<img width="1440" alt="screen shot 2015-08-26 at 11 44 59 am" src="https://cloud.githubusercontent.com/assets/8228624/9499948/1abb0af0-4be8-11e5-8a96-9d22b5eb2a84.png">

I love your work here, but this is a low priority Issue and we have some higher priority items I need you to look at.  In particular, Issue  #1250 is a critical path item.  Can you review the comments and chime in if you know a way to accomplish the photo uploads we are describing.

**Comment by gsouvik** [comment]
@bsaiken 
I think @WebDevJL and @damirius are on the right track on the photo upload issue and they have a head start. Conceptually I too have thought similarly. I just have one point in mind, reviewing some of the content like [this](http://www.html5rocks.com/en/features/storage) and [this](http://stackoverflow.com/questions/9487636/file-uploads-in-html5-offline-applications), it seems HTML5 storage is still very primitive and not supported across all the browsers, even some have size restrictions. Honestly if I were to develop this, I too would have to take a "trial and error" approach with no guarantee of exact solution to be found. But let me know if you still want me to experiment with it.

**Comment by gsouvik** [comment]
@bsaiken 
I've changed the wrapping code and have used native php method (rather than re-inventing the wheel) which now handles the wrapping. It tries to wrap around the character count (15 in our case) but searches for white space nearby so that words remain intact when broken into multiple lines.

Also I've introduced the row for the Units. Please note that the Analyte name must be of the format:
`Analyte Name (It's Unit) `
in order for the code to be able to handle it. Unit can have the following special characters:
@, #, $, %, *, /, +, -, _, ~
Let me know if you need any other and I shall add that to the regular expression.

And finally I've replicated all these changes for the Field Matrix to the Lab Analyte Matrix section. Code is pushed to feature_devsupport.

**Comment by bsaiken** [comment]
@gsouvik 
Now that's good stuff!  Do you need to also implement this on the Active Task tab?

**Comment by gsouvik** [comment]
@bsaiken 
Yes I missed that one, I'll change the the UI structure of `activetask/fieldData` to introduce the scroll area instead of pagination.

**Comment by bsaiken** [comment]
@gsouvik 
I don't know if this is fixed yet, but remember the default is checked, and the PM can then change the checked/unchecked state if the project is not active.  So, if I add new locations, or new field parameters, those additions would start out checked.

**Comment by gsouvik** [comment]
@bsaiken 
That feature is already up for the FT (#1207) . For example if the FT adds new location, in the field matrix every relation for that new location with all the field data available would be checked.

But do you want this to happen when PM adds new location/field data as well? That part in not implemented. Let me know and I shall code that.

**Comment by bsaiken** [comment]
@gsouvik 
Yes, let's clean it all up.

**Comment by gsouvik** [comment]
@bsaiken 
Further changes added are a follows:
1) Scrollable UI added to the `activetask/fieldData` screen.
2) Whenever PM adds a Location or Field data to a task, the relationship (for the matrix to be checked) gets auto created into the `field_analyte_location` table.

Code is pushed to the feature_devsupport branch. Please review and let me know your feedback.

**Comment by bsaiken** [comment]
@gsouvik 
Something fishy happened when I added a new Location (`Test for 1148`) as a FT.  There is no error, but the active task field matrix did not display properly.

<img width="1440" alt="screen shot 2015-08-31 at 8 20 11 am" src="https://cloud.githubusercontent.com/assets/8228624/9579556/2b87900e-4fb9-11e5-8782-02e49791e630.png">

**Comment by gsouvik** [comment]
@bsaiken 
Fixed the issue and pushed code to feature_devsupport.

**Comment by bsaiken** [comment]
@gsouvik 
 I just added a new Location and the default was not checked boxes.

<img width="1440" alt="screen shot 2015-08-31 at 9 32 52 am" src="https://cloud.githubusercontent.com/assets/8228624/9581166/574a1752-4fc3-11e5-9213-5730893476c5.png">

**Comment by gsouvik** [comment]
@bsaiken 
I've made videos to show the steps and how it looks on my local branch:
1) When PM adds location: http://sendvid.com/m3eqhars
2) When Technician adds a location: http://sendvid.com/oqou8s9j
If the result meets the requirement on these videos, I think you are not updated with the latest codebase. Please pull from feature_devsupport again and retry. Let me know how it went.

**Comment by bsaiken** [comment]
@gsouvik 
Still not working.  Try adding a new location using the highlighted button.

<img width="1440" alt="screen shot 2015-08-31 at 12 05 31 pm" src="https://cloud.githubusercontent.com/assets/8228624/9584792/e206d316-4fd8-11e5-90b5-02b248c97989.png">

**Comment by gsouvik** [comment]
@bsaiken 
Ok, I see the issue now, I missed adding the function to that button as I failed to realize that it directly adds location to a task. It should be now fixed. Please let me know all other places I might have missed from where a location could be assigned directly to a task and I shall add the function call to all those places.

**Comment by bsaiken** [comment]
@gsouvik 
It is also possible to add field parameters from the Task tab.
<img width="1440" alt="screen shot 2015-08-31 at 3 50 59 pm" src="https://cloud.githubusercontent.com/assets/8228624/9590104/35b80894-4ff8-11e5-8835-2cb1ce3e3cdc.png">
<img width="1440" alt="screen shot 2015-08-31 at 3 51 06 pm" src="https://cloud.githubusercontent.com/assets/8228624/9590114/433cdc7e-4ff8-11e5-8528-d61d2debd353.png">

**Comment by gsouvik** [comment]
@bsaiken 
Feature added to that button too.

**Comment by bsaiken** [comment]
@gsouvik 
OK - I think we have them all.
