### ISSUE TITLE
Disscussion Thread Milestone C(2) - Receive message from Service Provider

### ISSUE THREAD

**Issue by bsaiken** [FWAJL/FieldWorkManager#806]
This is similar to the requirements for Field Technicians.  However, messages from Service Providers may include attachments.  There should be a link to the attachment in the message history window.  Clicking the link shall open the attachement in a separate window.  To store attachments, use the file handling methods we have already implemented.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Do we have some dashboard for service providers? Or rather when I login as service provider do we have landing pages or something like that? I'm asking because I want to know where will they see their chatbox and how are we planing to send messages to PMs.
Code is already in place, everything we use for PMs can be reused for anyone else since our discussions table and code itself is just creating discussion thread between two users, since service providers like FTs and PMs are just type of users everything should work normally.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
We have no dashboard for Service Providers yet. 

Option one: we only have emails back an forth between the PM and service providers.  The PM would see the chatbox, the SP will only receive and send emails.  Is that feasible?  

Option two: we have emails only as notifications - to notify the recipient there is a message, then they can view and respond by clicking a link, taking then to their chatbox page.  The exception, or special case, would be new user confirmations.

What is easiest to implement?

Good timing to ask this, because today I am working on email message templates that would go with the various contexts (Field Technicians, Confirmation email for new users, etc.).  I should finish the templates document today or tomorrow.  Like many things on this website, I thought I knew what I wanted until we started doing it, now I am refining.

It would help me to know your thoughts.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I think that option two will be easier to implement since we would need some cron called scripts which will try to fetch incoming mails. Now that said, if we use them only as notifications we would still need those pages where SPs and FTs will see their messages. If we have that we may implement sending messages from there as well.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

Damir, I've not looked in details at the code but if you code it right, implementation should be very easy and building the page can be done quickly. The Mobile integration for FT will progress soon. Maybe, think about an implementation for the SPs? What do you say @bsaiken ?

Thank you! Keep up the good work guys :+1:

**Comment by bsaiken** [comment]
@damirius @FWAJL 

Having an email as notification with a link to the chatbox page is similar to what we have here in github - and part of the source of my inspiration.  Service Providers will, like Project Managers, access the site from a desktop environment, so emailing responses is not necessary.  If we implement Option 2 for SPs, this could be easily adapted for Clients (and other user types).  

In theory, FTs should have the website open the entire time they are working, as they will be interacting with the FT UI.  So even in their case, responding via email is not necessary. 
The PM's should not need to be notified via email, because they should be actively (or at the very least intermittently) monitoring the Task progress from their desktop.  

So really the only required emailing will be not notify recipients they have a message.  This is useful for SPs, since they would not normally be logged into he site.  However, for FTs, you are welcome to re-think emails.  We may just be able to put a notification bar in the header of the FT UI and get rid of the need for FTs to email.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

> @bsaiken said:
> We may just be able to put a notification bar in the header of the FT UI and get rid of the need for FTs to email.

This is definitely a feature that will be useful. An email or a web notification are both notifications. Therefore, where we decide to send an email, we can create a web notification and vice-versa. Do you see ? Therefore, we could add other type of notifications.

**Comment by bsaiken** [comment]
@FWAJL @damirius 

My idea was to eliminate the need for emailed notifications.  
However, we can't completely eliminate emails because SPs and Clients would not know they had a message.  FTs would know, because while they are working they are logged in much of the time. 

The way this relates to THIS Issue, is that SPs receive an email, notifying them of a message, but the way they respond is by logging into the site, then they respond with the chatbox.  Can we make is so that the link in the email includes login credentials (maybe encrypted) so they don't have to type in their username and password.  If they got the email, we know it's them.  Plus, they won't be having access to sensitive areas of the site at this point.

**Comment by damirius** [comment]
@FWAJL @bsaiken 

I've pushed new commit which contains chatbox page for SPs, it's on the feature_thread branch.
Like I mentioned, we don't have landing page for SPs, as the matter of fact we don't have any pages for SPs. In any case I've added serviceprovider/discussion page which SPs will use for communicating with PMs.
Here is the video: https://drive.google.com/file/d/0B7Laiv0PjSvDNWs5YVI2ZklFcmM/view?usp=sharing

Testing this will be little complicated but we will go step by step.
Login as PM, go to Tasks->List All.
Right click on some active task and choose 'Check task status'.
Go on communications tab.
If discussion isn't currently set or it doesn't exist at all, choose Service Provider from the first list and click on the arrow to add it to this discussion.
This will create new discussion or it will open existing one if we already started it before.
**The best way to test this is to create new discussion since we need `discussion_id` from the database for our next steps and if we create new one largest ID will be easiest to find**
In any case we need to remember that `discussion_id`.

Next steps are shown in the video.
Logout if you are still logged in as the PM.
Login as the SP. You will be redirected to serviceprovider/discussion page and it will show an error since we didn't specify discussion_id in the url.
Add "?discussion_id=XX" on the end of the current url, where XX is the ID of that discussion that we created as PM. Full address should look like "serviceprovider/discussion?discussion_id=5", if 5 is our id.
If everything is ok, page should be loaded and thread should be shown in the chat history like it does for PMs. You can send text messages or file attachments by uploading them from your machine.

Now if discussion_id isn't specified in the url we could show list of all discussion started with the logged in SP, so he can choose from the list and be redirected to this page we currently have.
Sending email notification with full address with discussion_id included is possible, but sending login credentials is a bit too complicated.
Users can't access role restricted pages if they aren't logged in, so sending them to serviceprovider/discussion page will result in an error even if we send login credentials in the url. We can maybe intercept all of that in the base controller and log them in before we check for permissions, but we would need to change a bit of the base framework code for that to work. Jeremie do you have any suggestions regarding this?

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I ran into several problems, some may be bugs.
I added a new Service Provider, and `user.user_value` was the same as a previous user.  See `user_value=53` in the attached.
![screen shot 2015-05-12 at 12 44 01 pm](https://cloud.githubusercontent.com/assets/8228624/7596706/9858ec94-f8a4-11e4-8131-00c18ebc7b10.png)

The second problem is that when I add a new Service Provider, the `user_role_id=4`.  Damir, in the code you submitted, you had the user_role_id set to 6.  So, I thought I would fix this by modifying auth.js so the new redirect, to serviceprovider/discussion, would take effect when `reply.role == '4'`.
However, that did not work.
I followed all other instructions.  Any ideas?
![screen shot 2015-05-12 at 12 56 01 pm](https://cloud.githubusercontent.com/assets/8228624/7597145/529c4780-f8a6-11e4-8a62-5edc7288cb8a.png)

**Comment by bsaiken** [comment]
@damirius @FWAJL  

> @damirius said:
> Now if discussion_id isn't specified in the url we could show list of all discussion started with the logged in SP

I have an alternate idea for this.  Since the SP will necessarily be getting an email every time there is a new message:  Include a link in the email that includes, along with the url, their username, password, and discussion_id.  Then they are automatically logged in and go to the correct discussion.  This info is not that sensitive, and they would already be somewhat protected by their local email password.  In fact, I do not think SPs would need to log in to have a discussion - just be given the discussion_id in the link.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

We need role 6 for services, role 4 is a visitor role, currently not used. So we need to add new `user_role` record, set `user_role_id` to 6 and `user_role_desc` to 'Service'. That said we need to update baiken_fwm_1_db_reset.sql file which we use for db reset.

Also just changing redirect in auth.js wont gonna cut it since we have the `role` attribute set in `routes.xml` for each UI path and on serviceprovider/discussion it is set to 6.

I have some problem with that video, google drive can't process it. So I have it here as well: http://webmup.com/ac36e/

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Oh yes, I forgot to change the routes.xml file!
There is still a problem that needs fixing - when I add a new SP, the code currently sets the `user_role_id` to 4.  Will the changes you suggested fix that?

**Comment by bsaiken** [comment]
@damirius @FWAJL 
OK - messages are working great, but I am unable to attach files by either party.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

You can do a pull on feature_thread branch. I've added option to login through url for serviceprovider/discussion.

You can visit url directly, it should look something like this: serviceprovider/discussion?discussion_id=6&username=wqe&password=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3g496lJL683
password is encrypted password from the db, username is user login and discussion id is the same as before. Jeremie will kill me when he see this :)

I don't know why attachments doesn't work honestly, they work for me like they should. If you can give me some screenshot or something similar of ajax call that is made to `file/upload` I could maybe find the bug. You can check it in developer tools in chrome under network->XHR tab when you upload new file.
Maybe it is some restricted file type? For now document table accepts this file types: "jpeg","jpg","gif","png","pdf"

**Comment by damirius** [comment]
@bsaiken @FWAJL 

Also I forgot to mention service creation script. We should change that so that new SPs are set to proper role. It doesn't matter now, since serviceprovider/discussion can be accessed by anyone now, but it would be great to set it up properly if we need some pages restricted only to SPs.

**Comment by bsaiken** [comment]
@damirius 
I tried the direct url, but I had to enter it twice for some reason.
Give me some time to look at the upload Issue.
Or, this may help:
![screen shot 2015-05-12 at 2 02 27 pm](https://cloud.githubusercontent.com/assets/8228624/7598528/b1448c6c-f8af-11e4-926c-20eb4cd1f293.png)
![screen shot 2015-05-12 at 2 02 42 pm](https://cloud.githubusercontent.com/assets/8228624/7598532/b8e71fb6-f8af-11e4-8125-2f684948fa02.png)

**Comment by damirius** [comment]
@bsaiken

OK, so file is being uploaded, but there is some problem with generation of absolute path which should be shown in the message. I'll take a look into it.

**Comment by bsaiken** [comment]
@damirius 
I just noticed another little bug - well, I guess it's not a bug just yet.
The menu item `Service Provider > Discussions`, meant for the Service Provider landing page, is available on the PM UI, and of course it should not be there.
![screen shot 2015-05-12 at 9 14 10 pm](https://cloud.githubusercontent.com/assets/8228624/7603669/2afd1164-f8ec-11e4-8021-e6bbffa4175e.png)

**Comment by bsaiken** [comment]
@damirius 
Per my previous comment - if the SP is only going to see the communications page, there is no need for a left menu, so we should hide it until (and if) we have at least two menu items.

I tested further with the database reset.  I am having the same problem.  I did confirm that the attached files are getting saved in the /Web/uploads/discussion folder.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

> @bsaiken said:
> Per my previous comment - if the SP is only going to see the communications page, there is no need for a left menu, so we should hide it until (and if) we have at least two menu items.

Is it a must-do for the end of May? there are many optimizations that we need to do for the Left Menu and that could be done later. Please create an issue if so.

Thank you.

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've added other function which should help us create full path to attached files. Can you tell me if attachments work now and if the full path is formatted correctly?
Also I've removed the serviceprovider menu.

**Comment by FWAJL** [comment]
@damirius @bsaiken 

I would add that the attachments should be clickable links. Otherwise, it works for both source of attachments. Good job! :+1:

**Comment by bsaiken** [comment]
@FWAJL @damirius 
> @FWAJL said:
> I would add that the attachments should be clickable links where the link text is the document title when not empty.

Attachments are handled in Issue #808.

**Comment by FWAJL** [comment]
@bsaiken @damirius 

The auto login is not a bad idea except this clear password. A solution would be a redirector url that works like this:

- The SP goes here: http://dev.fieldworkmanager.com/rd?guid=azhgf13v13bv213b123
- The redirector url goes here: http://dev.fieldworkmanager.com/serviceprovider/discussion?discussion_id=6&username=wqe&password=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3g496lJL683

***IMPORTANT:*** For security, we can ask the SP to confirm their identity with their email or a token provided in the email.

**Comment by bsaiken** [comment]
@damirius @FWAJL 
Just a note about the security.  It is important, but not for Service Provides - we will simply limit the SP access to pages that do not require security.
Clients will need strong security.  So, when we add security for Clients, we have the option of including it for SPs.
The auto-login has been created as Issue #985, but not yet assigned.

**Comment by bsaiken** [comment]
@FWAJL @damirius 

> Logout if you are still logged in as the PM.  Login as the SP. You will be redirected to serviceprovider/discussion page and it will show an error  since we didn't specify discussion_id in the url.
Add "?discussion_id=XX" on the end of the current url, where XX is the ID of that discussion that we created as PM. Full address should look like "serviceprovider/discussion?discussion_id=5"

 I have started a conversation with the SP "GTI", but I got an error when I tried to login and access the discussion.

![screen shot 2015-05-28 at 10 50 11 am](https://cloud.githubusercontent.com/assets/8228624/7866921/7753483e-0527-11e5-8d4e-ecf558acba5a.png)

**Comment by damirius** [comment]
@bsaiken @FWAJL 

I've tried to recreate it on both feature_mobile and dev branches without success. Also I've tried with previously created discussions and with new discussion to see if there is some problem with creating discussions now.
It seems that UserConnected session variable isn't set, that should be user object in session.
You used normal login screen to login with the service user? No username and/or password in the url right?

**Comment by bsaiken** [comment]
@damirius @FWAJL 
I found the problem.  Actually, it is a couple of problems.  I am creating a new Issue for each.
1)  Issue #1022.  The `user_role` table must be modified.
2) Issue #1023. New SP users are being created, but the `user_role_id` is still being set to 4 - it should be 6.
Let's fix those items then I'll check again.
